import { Project } from "../types/interface";

const bannersNft: Project = {
    name: "Banners (for Adventures)",
    description: "Banners is 25000 text only NFTs that serve as society before the Great War. A Banner is a key to future graphic airdrops and projects built in the Exodus epoch.",
    whatToDo: [
        {
            content: "Site",
            url: "https://bannersnft.com/"
        },
        {
            content: "Coming Soon",
            url: "https://opensea.io/BannersNFT"
        },
    ],
    website: {
        url: "https://bannersnft.com/"
    },
    twitter: {
        url: "https://twitter.com/BannersNft"
    },
    discord: {
        url: "https://discord.gg/MYxGU7rjY4"
    },
    github: {
        url: "https://github.com/farque65/BannersNFT"
    }
};

const cryptoodleLoot: Project = {
    name: "Toodle Loot Bag",
    description:
        "10,000 programmable Loot Bags engineered by Cryptoodles used to advance the technology of civilizations.",
    whatToDo: [
        {
            content: "Claim Free BAG",
            url: "https://docs.cryptoodles.com/toodl-nfts/redeeming-loot-bag-nfts"
        },
        {
            content: "Trade",
            url: "https://opensea.io/collection/toodle-loot-bag"
        }

    ],
    website: {
        url: "https://cryptoodles.com"
    },
    twitter: {
        url: "https://twitter.com/cryptoodles"
    },
    discord: {
        url: "https://discord.com/invite/g9SnvzdFs2"
    },
    opensea: {
        url: "https://opensea.io/collection/toodle-loot-bag"
    },
    contract: {
        content: "0x2a16107ea0d28ae822168c8bb3ef5460b1924a78"
    },
    github: {
        url: "https://github.com/cryptoodles"
    }
};

const nProject: Project = {
    name: "Minting",
    description: "Launch 1501 NFTs that are randomly generated by our code from the famous speech of the Martin Luter King Junior 'I Have a Dream'.",
    whatToDo: [
        {
            content: "Beginning",
            url: "https://opensea.io/collection/n-project"
        },
    ]
};

const treasure: Project = {
    name: "Secondary Markets",
    description: "We are in contact with two marketplaces, Magic Eden and Solport nft marketplace. ",
    whatToDo: [
        {
            content: "Listing",
            url: "https://opensea.io/collection/treasure-for-loot"
        },
    ],
};
const dopeWars: Project = {
    name: "Promote Black Art",
    description: "20% of the Mint proceeds and royalties go towards social causes and promoting black art in Solana NFTs.",
    whatToDo: [
        {
            content: "Donating",
            url: "https://opensea.io/collection/dope-v4"
        },
    ],
    
};

const adventureCards: Project = {
    name: "NFT Launches on Solana",
    description: "We will invest 30% of our revenue to provide the infrastructure for any artist to launch it's own collectible art on Solana. The service will be completely Free of charge and welcoming to all artists across the globe.",
    whatToDo: [
        {
            content: "Launchpad",
            url: "https://opensea.io/collection/adventure-cards"
        },
    ],
};
export {
    cryptoodleLoot,
    nProject,
    treasure,
    dopeWars,
    adventureCards,
    bannersNft
}
