import { Project } from "../types/interface";

const roadmap_1: Project = {
    name: "B-DAO",
    description: "Access to each 1501 will give you governance to the DAO.",
    whatToDo: [
        {
            content: "DAO",
            url: "https://the1501project.com/"
        },
    ],
    github: {
        url: "https://github.com/The1501Project"
    }
};

const roadmap_2: Project = {
    name: "Token and NFT Staking",
    description:
        "Launh our own $FREEDOM token and create utility to allow the staking of NFTs to earn.",
    whatToDo: [
    {
            content: "Token and Staking",
            url: "https://the1501project.com/"
        },
    ],

};

const roadmap_3: Project = {
    name: "Minting",
    description: "Launch 1501 NFTs that are randomly generated by our code from the famous speech of the Martin Luter King Junior 'I Have a Dream'.",
    whatToDo: [
        {
            content: "Beginning",
            url: "https://the1501project.com/"
        },
    ]
};

const roadmap_4: Project = {
    name: "Secondary Markets",
    description: "We are in contact with two marketplaces, Magic Eden and Solport nft marketplace. ",
    whatToDo: [
        {
            content: "Listing",
            url: "https://the1501project.com/"
        },
    ],
};
const roadmap_5: Project = {
    name: "Promote Black Art",
    description: "20% of the Mint proceeds and royalties go towards social causes and promoting black art in Solana NFTs.",
    whatToDo: [
        {
            content: "Donating",
            url: "https://the1501project.com/"
        },
    ],

};

const roadmap_6: Project = {
    name: "NFT Launches on Solana",
    description: "We will invest 30% of our revenue to provide the infrastructure for any artist to launch it's own collectible art on Solana.",
    whatToDo: [
        {
            content: "Launchpad",
            url: "https://the1501project.com/"
        },
    ],
};

export const roadmapList = [
    {
        name: "",
        description: "",
        project: [
            roadmap_1,
            roadmap_2,
            roadmap_3,
            roadmap_4,
            roadmap_5,
            roadmap_6,
        ],
    },
];
